// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for EcommercePage documents */
interface EcommercepageDocumentData {
    /**
     * Title field in *EcommercePage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: ecommercepage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Slice Zone field in *EcommercePage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: ecommercepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<EcommercepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *EcommercePage → Slice Zone*
 *
 */
type EcommercepageDocumentDataSlicesSlice = ScaleYourEcommerceSlice | ExploreWorksSlice | EcomHeroSlice | GreatDigitalExperienceSlice;
/**
 * EcommercePage document from Prismic
 *
 * - **API ID**: `ecommercepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EcommercepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<EcommercepageDocumentData>, "ecommercepage", Lang>;
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Title field in *Homepage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = HeroSlice | RelationshipsSlice | ScaleYourEcommerceSlice | ExploreWorksSlice | DesignShowcaseSlice | BespokeServicesSlice | CertificationSlice | SuccessStoriesSlice | LocationShowCaseSlice | NewsLetterSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for WorksPage documents */
interface WorkspageDocumentData {
    /**
     * Title field in *WorksPage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: workspage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Slice Zone field in *WorksPage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: workspage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<WorkspageDocumentDataSlicesSlice>;
}
/**
 * Slice for *WorksPage → Slice Zone*
 *
 */
type WorkspageDocumentDataSlicesSlice = WorksHeroSlice | WorksShowCaseSlice;
/**
 * WorksPage document from Prismic
 *
 * - **API ID**: `workspage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkspageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<WorkspageDocumentData>, "workspage", Lang>;
export type AllDocumentTypes = EcommercepageDocument | HomepageDocument | WorkspageDocument;
/**
 * Primary content in BespokeServices → Primary
 *
 */
interface BespokeServicesSliceDefaultPrimary {
    /**
     * Title field in *BespokeServices → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: bespoke_services.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Default variation for BespokeServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: `BespokeServices`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BespokeServicesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<BespokeServicesSliceDefaultPrimary>, never>;
/**
 * Slice variation for *BespokeServices*
 *
 */
type BespokeServicesSliceVariation = BespokeServicesSliceDefault;
/**
 * BespokeServices Shared Slice
 *
 * - **API ID**: `bespoke_services`
 * - **Description**: `BespokeServices`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BespokeServicesSlice = prismicT.SharedSlice<"bespoke_services", BespokeServicesSliceVariation>;
/**
 * Primary content in Certification → Primary
 *
 */
interface CertificationSliceDefaultPrimary {
    /**
     * Title field in *Certification → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: certification.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Default variation for Certification Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Certification`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CertificationSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CertificationSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Certification*
 *
 */
type CertificationSliceVariation = CertificationSliceDefault;
/**
 * Certification Shared Slice
 *
 * - **API ID**: `certification`
 * - **Description**: `Certification`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CertificationSlice = prismicT.SharedSlice<"certification", CertificationSliceVariation>;
/**
 * Primary content in DesignShowcase → Primary
 *
 */
interface DesignShowcaseSliceDefaultPrimary {
    /**
     * Title field in *DesignShowcase → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: design_showcase.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Default variation for DesignShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: `DesignShowcase`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DesignShowcaseSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<DesignShowcaseSliceDefaultPrimary>, never>;
/**
 * Slice variation for *DesignShowcase*
 *
 */
type DesignShowcaseSliceVariation = DesignShowcaseSliceDefault;
/**
 * DesignShowcase Shared Slice
 *
 * - **API ID**: `design_showcase`
 * - **Description**: `DesignShowcase`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DesignShowcaseSlice = prismicT.SharedSlice<"design_showcase", DesignShowcaseSliceVariation>;
/**
 * Primary content in EcomHero → Primary
 *
 */
interface EcomHeroSliceDefaultPrimary {
    /**
     * ImageA field in *EcomHero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: ecom_hero.primary.imagea
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    imagea: prismicT.ImageField<never>;
    /**
     * ImageB field in *EcomHero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: ecom_hero.primary.imageb
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    imageb: prismicT.ImageField<never>;
    /**
     * ImageC field in *EcomHero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: ecom_hero.primary.imagec
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    imagec: prismicT.ImageField<never>;
}
/**
 * Default variation for EcomHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `EcomHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EcomHeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<EcomHeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *EcomHero*
 *
 */
type EcomHeroSliceVariation = EcomHeroSliceDefault;
/**
 * EcomHero Shared Slice
 *
 * - **API ID**: `ecom_hero`
 * - **Description**: `EcomHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EcomHeroSlice = prismicT.SharedSlice<"ecom_hero", EcomHeroSliceVariation>;
/**
 * Primary content in ExploreWorks → Primary
 *
 */
interface ExploreWorksSliceDefaultPrimary {
    /**
     * title field in *ExploreWorks → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: explore_works.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
}
/**
 * Default variation for ExploreWorks Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ExploreWorks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ExploreWorksSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ExploreWorksSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ExploreWorks*
 *
 */
type ExploreWorksSliceVariation = ExploreWorksSliceDefault;
/**
 * ExploreWorks Shared Slice
 *
 * - **API ID**: `explore_works`
 * - **Description**: `ExploreWorks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ExploreWorksSlice = prismicT.SharedSlice<"explore_works", ExploreWorksSliceVariation>;
/**
 * Primary content in GreatDigitalExperience → Primary
 *
 */
interface GreatDigitalExperienceSliceDefaultPrimary {
    /**
     * Title field in *GreatDigitalExperience → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: great_digital_experience.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in GreatDigitalExperience → Items
 *
 */
export interface GreatDigitalExperienceSliceDefaultItem {
    /**
     * logo field in *GreatDigitalExperience → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: great_digital_experience.items[].logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * Description field in *GreatDigitalExperience → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: great_digital_experience.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * CTA Text field in *GreatDigitalExperience → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: great_digital_experience.items[].cta_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    cta_text: prismicT.RichTextField;
}
/**
 * Default variation for GreatDigitalExperience Slice
 *
 * - **API ID**: `default`
 * - **Description**: `GreatDigitalExperience`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GreatDigitalExperienceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<GreatDigitalExperienceSliceDefaultPrimary>, Simplify<GreatDigitalExperienceSliceDefaultItem>>;
/**
 * Slice variation for *GreatDigitalExperience*
 *
 */
type GreatDigitalExperienceSliceVariation = GreatDigitalExperienceSliceDefault;
/**
 * GreatDigitalExperience Shared Slice
 *
 * - **API ID**: `great_digital_experience`
 * - **Description**: `GreatDigitalExperience`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GreatDigitalExperienceSlice = prismicT.SharedSlice<"great_digital_experience", GreatDigitalExperienceSliceVariation>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
    /**
     * Title field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: hero.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Description field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: hero.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Highlight Description field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.highlight_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    highlight_description: prismicT.RichTextField;
    /**
     * Hero Showcase Logo field in *Hero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.hero_showcase_logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    hero_showcase_logo: prismicT.ImageField<never>;
}
/**
 * Item in Hero → Items
 *
 */
export interface HeroSliceDefaultItem {
    /**
     * Hero Small Logo Showcase field in *Hero → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.items[].hero_small_logo_showcase
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    hero_small_logo_showcase: prismicT.ImageField<never>;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, Simplify<HeroSliceDefaultItem>>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceHeroSecondaryPrimary {
    /**
     * Title field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: hero.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Description field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: hero.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Highlight Description field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.highlight_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    highlight_description: prismicT.RichTextField;
    /**
     * Hero Showcase Video field in *Hero → Primary*
     *
     * - **Field Type**: Embed
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.hero_showcase_video
     * - **Documentation**: https://prismic.io/docs/core-concepts/embed
     *
     */
    hero_showcase_video: prismicT.EmbedField;
    /**
     * secondaryHero field in *Hero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.secondaryhero
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    secondaryhero: prismicT.ImageField<never>;
}
/**
 * Item in Hero → Items
 *
 */
export interface HeroSliceHeroSecondaryItem {
    /**
     * Hero Small Logo Showcase field in *Hero → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.items[].hero_small_logo_showcase
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    hero_small_logo_showcase: prismicT.ImageField<never>;
}
/**
 * Hero-secondary variation for Hero Slice
 *
 * - **API ID**: `heroSecondary`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceHeroSecondary = prismicT.SharedSliceVariation<"heroSecondary", Simplify<HeroSliceHeroSecondaryPrimary>, Simplify<HeroSliceHeroSecondaryItem>>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceHeroSecondary;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Primary content in LocationShowCase → Primary
 *
 */
interface LocationShowCaseSliceDefaultPrimary {
    /**
     * Title field in *LocationShowCase → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: location_show_case.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *LocationShowCase → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: location_show_case.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for LocationShowCase Slice
 *
 * - **API ID**: `default`
 * - **Description**: `LocationShowCase`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LocationShowCaseSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<LocationShowCaseSliceDefaultPrimary>, never>;
/**
 * Slice variation for *LocationShowCase*
 *
 */
type LocationShowCaseSliceVariation = LocationShowCaseSliceDefault;
/**
 * LocationShowCase Shared Slice
 *
 * - **API ID**: `location_show_case`
 * - **Description**: `LocationShowCase`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LocationShowCaseSlice = prismicT.SharedSlice<"location_show_case", LocationShowCaseSliceVariation>;
/**
 * Primary content in NewsLetter → Primary
 *
 */
interface NewsLetterSliceDefaultPrimary {
    /**
     * Title field in *NewsLetter → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: news_letter.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *NewsLetter → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: news_letter.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for NewsLetter Slice
 *
 * - **API ID**: `default`
 * - **Description**: `NewsLetter`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NewsLetterSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<NewsLetterSliceDefaultPrimary>, never>;
/**
 * Slice variation for *NewsLetter*
 *
 */
type NewsLetterSliceVariation = NewsLetterSliceDefault;
/**
 * NewsLetter Shared Slice
 *
 * - **API ID**: `news_letter`
 * - **Description**: `NewsLetter`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NewsLetterSlice = prismicT.SharedSlice<"news_letter", NewsLetterSliceVariation>;
/**
 * Item in Relationships → Items
 *
 */
export interface RelationshipsSliceDefaultItem {
    /**
     * Relationships Logo Showcase field in *Relationships → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: relationships.items[].relationships_logo_showcase
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    relationships_logo_showcase: prismicT.ImageField<never>;
}
/**
 * Default variation for Relationships Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Relationships`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RelationshipsSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<RelationshipsSliceDefaultItem>>;
/**
 * Slice variation for *Relationships*
 *
 */
type RelationshipsSliceVariation = RelationshipsSliceDefault;
/**
 * Relationships Shared Slice
 *
 * - **API ID**: `relationships`
 * - **Description**: `Relationships`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RelationshipsSlice = prismicT.SharedSlice<"relationships", RelationshipsSliceVariation>;
/**
 * Item in ScaleYourEcommerce → Items
 *
 */
export interface ScaleYourEcommerceSliceDefaultItem {
    /**
     * Description field in *ScaleYourEcommerce → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: scale_your_ecommerce.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Logo field in *ScaleYourEcommerce → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: scale_your_ecommerce.items[].logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
}
/**
 * Default variation for ScaleYourEcommerce Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ScaleYourEcommerce`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ScaleYourEcommerceSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<ScaleYourEcommerceSliceDefaultItem>>;
/**
 * Slice variation for *ScaleYourEcommerce*
 *
 */
type ScaleYourEcommerceSliceVariation = ScaleYourEcommerceSliceDefault;
/**
 * ScaleYourEcommerce Shared Slice
 *
 * - **API ID**: `scale_your_ecommerce`
 * - **Description**: `ScaleYourEcommerce`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ScaleYourEcommerceSlice = prismicT.SharedSlice<"scale_your_ecommerce", ScaleYourEcommerceSliceVariation>;
/**
 * Item in SuccessStories → Items
 *
 */
export interface SuccessStoriesSliceDefaultItem {
    /**
     * Tab title field in *SuccessStories → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: success_stories.items[].tab_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    tab_title: prismicT.ImageField<never>;
    /**
     * Tab Content Title field in *SuccessStories → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: success_stories.items[].tab_content_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    tab_content_title: prismicT.RichTextField;
    /**
     * Tab Content Description field in *SuccessStories → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: success_stories.items[].tab_content_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    tab_content_description: prismicT.RichTextField;
    /**
     * Tab Content Image field in *SuccessStories → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: success_stories.items[].tab_content_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    tab_content_image: prismicT.ImageField<never>;
}
/**
 * Default variation for SuccessStories Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SuccessStories`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SuccessStoriesSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<SuccessStoriesSliceDefaultItem>>;
/**
 * Slice variation for *SuccessStories*
 *
 */
type SuccessStoriesSliceVariation = SuccessStoriesSliceDefault;
/**
 * SuccessStories Shared Slice
 *
 * - **API ID**: `success_stories`
 * - **Description**: `SuccessStories`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SuccessStoriesSlice = prismicT.SharedSlice<"success_stories", SuccessStoriesSliceVariation>;
/**
 * Primary content in WorksHero → Primary
 *
 */
interface WorksHeroSliceDefaultPrimary {
    /**
     * Title field in *WorksHero → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: works_hero.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *WorksHero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: works_hero.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for WorksHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `WorksHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WorksHeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<WorksHeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *WorksHero*
 *
 */
type WorksHeroSliceVariation = WorksHeroSliceDefault;
/**
 * WorksHero Shared Slice
 *
 * - **API ID**: `works_hero`
 * - **Description**: `WorksHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WorksHeroSlice = prismicT.SharedSlice<"works_hero", WorksHeroSliceVariation>;
/**
 * Primary content in WorksShowCase → Primary
 *
 */
interface WorksShowCaseSliceDefaultPrimary {
    /**
     * Title field in *WorksShowCase → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: works_show_case.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in WorksShowCase → Items
 *
 */
export interface WorksShowCaseSliceDefaultItem {
    /**
     * Image A field in *WorksShowCase → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].image_a
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_a: prismicT.ImageField<never>;
    /**
     * Img A Tag A field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_a_tag_a
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_a_tag_a: prismicT.RichTextField;
    /**
     * Img A Tag B field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_a_tag_b
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_a_tag_b: prismicT.RichTextField;
    /**
     * Img A Tag C field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_a_tag_c
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_a_tag_c: prismicT.RichTextField;
    /**
     * Img A Title field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_a_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_a_title: prismicT.RichTextField;
    /**
     * Img A Description field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_a_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_a_description: prismicT.RichTextField;
    /**
     * Img A Tag Category field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_a_tag_category
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_a_tag_category: prismicT.RichTextField;
    /**
     * Image B field in *WorksShowCase → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].image_b
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_b: prismicT.ImageField<never>;
    /**
     * Img B Tag A field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_b_tag_a
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_b_tag_a: prismicT.RichTextField;
    /**
     * Img B Tag B field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_b_tag_b
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_b_tag_b: prismicT.RichTextField;
    /**
     * Img B Tag C field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_b_tag_c
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_b_tag_c: prismicT.RichTextField;
    /**
     * Img B Title field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_b_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_b_title: prismicT.RichTextField;
    /**
     * Img B Description field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_b_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_b_description: prismicT.RichTextField;
    /**
     * Img B Tag Category field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_b_tag_category
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_b_tag_category: prismicT.RichTextField;
    /**
     * Image C field in *WorksShowCase → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].image_c
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_c: prismicT.ImageField<never>;
    /**
     * Img C Tag A field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_c_tag_a
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_c_tag_a: prismicT.RichTextField;
    /**
     * Img C Tag B field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_c_tag_b
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_c_tag_b: prismicT.RichTextField;
    /**
     * Img C Tag C field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_c_tag_c
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_c_tag_c: prismicT.RichTextField;
    /**
     * Img C Title field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_c_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_c_title: prismicT.RichTextField;
    /**
     * Img C Description field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_c_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_c_description: prismicT.RichTextField;
    /**
     * Img C Tag Category field in *WorksShowCase → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: works_show_case.items[].img_c_tag_category
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    img_c_tag_category: prismicT.RichTextField;
}
/**
 * Default variation for WorksShowCase Slice
 *
 * - **API ID**: `default`
 * - **Description**: `WorksShowCase`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WorksShowCaseSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<WorksShowCaseSliceDefaultPrimary>, Simplify<WorksShowCaseSliceDefaultItem>>;
/**
 * Slice variation for *WorksShowCase*
 *
 */
type WorksShowCaseSliceVariation = WorksShowCaseSliceDefault;
/**
 * WorksShowCase Shared Slice
 *
 * - **API ID**: `works_show_case`
 * - **Description**: `WorksShowCase`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type WorksShowCaseSlice = prismicT.SharedSlice<"works_show_case", WorksShowCaseSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { EcommercepageDocumentData, EcommercepageDocumentDataSlicesSlice, EcommercepageDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, WorkspageDocumentData, WorkspageDocumentDataSlicesSlice, WorkspageDocument, AllDocumentTypes, BespokeServicesSliceDefaultPrimary, BespokeServicesSliceDefault, BespokeServicesSliceVariation, BespokeServicesSlice, CertificationSliceDefaultPrimary, CertificationSliceDefault, CertificationSliceVariation, CertificationSlice, DesignShowcaseSliceDefaultPrimary, DesignShowcaseSliceDefault, DesignShowcaseSliceVariation, DesignShowcaseSlice, EcomHeroSliceDefaultPrimary, EcomHeroSliceDefault, EcomHeroSliceVariation, EcomHeroSlice, ExploreWorksSliceDefaultPrimary, ExploreWorksSliceDefault, ExploreWorksSliceVariation, ExploreWorksSlice, GreatDigitalExperienceSliceDefaultPrimary, GreatDigitalExperienceSliceDefaultItem, GreatDigitalExperienceSliceDefault, GreatDigitalExperienceSliceVariation, GreatDigitalExperienceSlice, HeroSliceDefaultPrimary, HeroSliceDefaultItem, HeroSliceDefault, HeroSliceHeroSecondaryPrimary, HeroSliceHeroSecondaryItem, HeroSliceHeroSecondary, HeroSliceVariation, HeroSlice, LocationShowCaseSliceDefaultPrimary, LocationShowCaseSliceDefault, LocationShowCaseSliceVariation, LocationShowCaseSlice, NewsLetterSliceDefaultPrimary, NewsLetterSliceDefault, NewsLetterSliceVariation, NewsLetterSlice, RelationshipsSliceDefaultItem, RelationshipsSliceDefault, RelationshipsSliceVariation, RelationshipsSlice, ScaleYourEcommerceSliceDefaultItem, ScaleYourEcommerceSliceDefault, ScaleYourEcommerceSliceVariation, ScaleYourEcommerceSlice, SuccessStoriesSliceDefaultItem, SuccessStoriesSliceDefault, SuccessStoriesSliceVariation, SuccessStoriesSlice, WorksHeroSliceDefaultPrimary, WorksHeroSliceDefault, WorksHeroSliceVariation, WorksHeroSlice, WorksShowCaseSliceDefaultPrimary, WorksShowCaseSliceDefaultItem, WorksShowCaseSliceDefault, WorksShowCaseSliceVariation, WorksShowCaseSlice };
    }
}
