// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Title field in *Homepage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = HeroSlice | RelationshipsSlice | ScaleYourEcommerceSlice | ExploreWorksSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
export type AllDocumentTypes = HomepageDocument;
/**
 * Item in ExploreWorks → Items
 *
 */
export interface ExploreWorksSliceDefaultItem {
    /**
     * Explore Works Showcase Description field in *ExploreWorks → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: explore_works.items[].explore_works_showcase_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    explore_works_showcase_description: prismicT.RichTextField;
    /**
     * Explore Works Showcase Tag A field in *ExploreWorks → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: explore_works.items[].explore_works_showcase_tag_a
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    explore_works_showcase_tag_a: prismicT.RichTextField;
    /**
     * Explore Works Showcase Tag B field in *ExploreWorks → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: explore_works.items[].explore_works_showcase_tag_b
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    explore_works_showcase_tag_b: prismicT.RichTextField;
    /**
     * Explore Works Showcase Image field in *ExploreWorks → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: explore_works.items[].explore_works_showcase_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    explore_works_showcase_image: prismicT.ImageField<never>;
    /**
     * Explore Works Icon field in *ExploreWorks → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: explore_works.items[].explore_works_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    explore_works_icon: prismicT.ImageField<never>;
    /**
     * Explore Works Count field in *ExploreWorks → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: explore_works.items[].explore_works_count
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    explore_works_count: prismicT.RichTextField;
}
/**
 * Default variation for ExploreWorks Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ExploreWorks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ExploreWorksSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<ExploreWorksSliceDefaultItem>>;
/**
 * Slice variation for *ExploreWorks*
 *
 */
type ExploreWorksSliceVariation = ExploreWorksSliceDefault;
/**
 * ExploreWorks Shared Slice
 *
 * - **API ID**: `explore_works`
 * - **Description**: `ExploreWorks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ExploreWorksSlice = prismicT.SharedSlice<"explore_works", ExploreWorksSliceVariation>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
    /**
     * Title field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: hero.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Description field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: hero.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Highlight Description field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.highlight_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    highlight_description: prismicT.RichTextField;
    /**
     * Hero Showcase Logo field in *Hero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.hero_showcase_logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    hero_showcase_logo: prismicT.ImageField<never>;
}
/**
 * Item in Hero → Items
 *
 */
export interface HeroSliceDefaultItem {
    /**
     * Hero Small Logo Showcase field in *Hero → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.items[].hero_small_logo_showcase
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    hero_small_logo_showcase: prismicT.ImageField<never>;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, Simplify<HeroSliceDefaultItem>>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceHeroSecondaryPrimary {
    /**
     * Title field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: hero.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Description field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: hero.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Highlight Description field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.highlight_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    highlight_description: prismicT.RichTextField;
    /**
     * Hero Showcase Video field in *Hero → Primary*
     *
     * - **Field Type**: Embed
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.hero_showcase_video
     * - **Documentation**: https://prismic.io/docs/core-concepts/embed
     *
     */
    hero_showcase_video: prismicT.EmbedField;
    /**
     * secondaryHero field in *Hero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.secondaryhero
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    secondaryhero: prismicT.ImageField<never>;
}
/**
 * Item in Hero → Items
 *
 */
export interface HeroSliceHeroSecondaryItem {
    /**
     * Hero Small Logo Showcase field in *Hero → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.items[].hero_small_logo_showcase
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    hero_small_logo_showcase: prismicT.ImageField<never>;
}
/**
 * Hero-secondary variation for Hero Slice
 *
 * - **API ID**: `heroSecondary`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceHeroSecondary = prismicT.SharedSliceVariation<"heroSecondary", Simplify<HeroSliceHeroSecondaryPrimary>, Simplify<HeroSliceHeroSecondaryItem>>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceHeroSecondary;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Item in Relationships → Items
 *
 */
export interface RelationshipsSliceDefaultItem {
    /**
     * Relationships Logo Showcase field in *Relationships → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: relationships.items[].relationships_logo_showcase
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    relationships_logo_showcase: prismicT.ImageField<never>;
}
/**
 * Default variation for Relationships Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Relationships`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RelationshipsSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<RelationshipsSliceDefaultItem>>;
/**
 * Slice variation for *Relationships*
 *
 */
type RelationshipsSliceVariation = RelationshipsSliceDefault;
/**
 * Relationships Shared Slice
 *
 * - **API ID**: `relationships`
 * - **Description**: `Relationships`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RelationshipsSlice = prismicT.SharedSlice<"relationships", RelationshipsSliceVariation>;
/**
 * Primary content in ScaleYourEcommerce → Primary
 *
 */
interface ScaleYourEcommerceSliceDefaultPrimary {
    /**
     * Title field in *ScaleYourEcommerce → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: scale_your_ecommerce.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *ScaleYourEcommerce → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: scale_your_ecommerce.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for ScaleYourEcommerce Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ScaleYourEcommerce`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ScaleYourEcommerceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ScaleYourEcommerceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ScaleYourEcommerce*
 *
 */
type ScaleYourEcommerceSliceVariation = ScaleYourEcommerceSliceDefault;
/**
 * ScaleYourEcommerce Shared Slice
 *
 * - **API ID**: `scale_your_ecommerce`
 * - **Description**: `ScaleYourEcommerce`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ScaleYourEcommerceSlice = prismicT.SharedSlice<"scale_your_ecommerce", ScaleYourEcommerceSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, AllDocumentTypes, ExploreWorksSliceDefaultItem, ExploreWorksSliceDefault, ExploreWorksSliceVariation, ExploreWorksSlice, HeroSliceDefaultPrimary, HeroSliceDefaultItem, HeroSliceDefault, HeroSliceHeroSecondaryPrimary, HeroSliceHeroSecondaryItem, HeroSliceHeroSecondary, HeroSliceVariation, HeroSlice, RelationshipsSliceDefaultItem, RelationshipsSliceDefault, RelationshipsSliceVariation, RelationshipsSlice, ScaleYourEcommerceSliceDefaultPrimary, ScaleYourEcommerceSliceDefault, ScaleYourEcommerceSliceVariation, ScaleYourEcommerceSlice };
    }
}
