// Code generated by Slice Machine. DO NOT EDIT.

import BespokeServices from './BespokeServices';
import Certification from './Certification';
import DesignShowcase from './DesignShowcase';
import EcomHero from './EcomHero';
import ExploreWorks from './ExploreWorks';
import GreatDigitalExperience from './GreatDigitalExperience';
import Hero from './Hero';
import LocationShowCase from './LocationShowCase';
import NewsLetter from './NewsLetter';
import Relationships from './Relationships';
import ScaleYourEcommerce from './ScaleYourEcommerce';
import SuccessStories from './SuccessStories';
import WorksHero from './WorksHero';
import WorksShowCase from './WorksShowCase';

export {
	BespokeServices,
	Certification,
	DesignShowcase,
	EcomHero,
	ExploreWorks,
	GreatDigitalExperience,
	Hero,
	LocationShowCase,
	NewsLetter,
	Relationships,
	ScaleYourEcommerce,
	SuccessStories,
	WorksHero,
	WorksShowCase,
};

export const components = {
	bespoke_services: BespokeServices,
	certification: Certification,
	design_showcase: DesignShowcase,
	ecom_hero: EcomHero,
	explore_works: ExploreWorks,
	great_digital_experience: GreatDigitalExperience,
	hero: Hero,
	location_show_case: LocationShowCase,
	news_letter: NewsLetter,
	relationships: Relationships,
	scale_your_ecommerce: ScaleYourEcommerce,
	success_stories: SuccessStories,
	works_hero: WorksHero,
	works_show_case: WorksShowCase,
};
