// Code generated by Slice Machine. DO NOT EDIT.

import DesignShowcase from './DesignShowcase';
import ExploreWorks from './ExploreWorks';
import Hero from './Hero';
import Relationships from './Relationships';
import ScaleYourEcommerce from './ScaleYourEcommerce';

export {
	DesignShowcase,
	ExploreWorks,
	Hero,
	Relationships,
	ScaleYourEcommerce,
};

export const components = {
	design_showcase: DesignShowcase,
	explore_works: ExploreWorks,
	hero: Hero,
	relationships: Relationships,
	scale_your_ecommerce: ScaleYourEcommerce,
};
