// Code generated by Slice Machine. DO NOT EDIT.

import BespokeServices from './BespokeServices';
import Certification from './Certification';
import DesignShowcase from './DesignShowcase';
import ExploreWorks from './ExploreWorks';
import Hero from './Hero';
import Relationships from './Relationships';
import ScaleYourEcommerce from './ScaleYourEcommerce';
import SuccessStories from './SuccessStories';

export {
	BespokeServices,
	Certification,
	DesignShowcase,
	ExploreWorks,
	Hero,
	Relationships,
	ScaleYourEcommerce,
	SuccessStories,
};

export const components = {
	bespoke_services: BespokeServices,
	certification: Certification,
	design_showcase: DesignShowcase,
	explore_works: ExploreWorks,
	hero: Hero,
	relationships: Relationships,
	scale_your_ecommerce: ScaleYourEcommerce,
	success_stories: SuccessStories,
};
